### ISSUE TITLE
mpo_500.urdf

### ISSUE THREAD

**Issue by vkuehn** [neobotix/neo_simulation2#41]
Hi,

on a fresh installation of ros2 foxy rviz2 ca not load 
https://github.com/neobotix/neo_simulation2/blob/main/robots/mpo_500/mpo_500.urdf

as it complains 
No transform from [base_footprint] to [map]
No transform from [base_link] to [map]
...

**Comment by padhupradheep** [comment]
Hey, on the left side of the RViz you will see the Display panes. Under the display pane, you will see the global options, under that you have to select odom under fixed frame.

**Comment by padhupradheep** [comment]
I will suggest you to use Galactic rather than Foxy.

**Comment by vkuehn** [comment]
this does only change the view and not solve the complain for the missing links.

Foxy is the LTS version thought. Any particular reason to change for Galactic

**Comment by padhupradheep** [comment]
The navigation stack is much mature for Galactic compared to Foxy and some of the features aren’t available. We haven’t been looking into foxy for a while as well. All the features are being targeted for Galactic. 

But if you want to use foxy, I’ll try to see and backport the developments that we made for galactic

**Comment by vkuehn** [comment]
okay I might not be the most important person. Was just curious about the mp0_500 as it was used in a life class of the theconstructsim.com

**Comment by vkuehn** [comment]
@padhupradheep ok thanks. However Foxy is the LTS version and therefore should be supported first. I checked up some of the other tutorials and  failed also. 
Let me know once you have a new URDF and I will check again with foxy.
Would be great to have a working simulation installed from scratch here

**Comment by padhupradheep** [comment]
> However Foxy is the LTS version 

That is true indeed, but ROS-2 is maturing every day and the developments for the domain we are in, does not target very much for Foxy.  Rather there is a new LTS release called Humble targetting Ubuntu 22.04

> and therefore should be supported first.

I totally understand your concern. 

>  Let me know once you have a new URDF and I will check again with foxy.

The URDF is not going to change but some of the configs and executable just need an upgrade based on the updates we made in the past for the other latest distros. 

In any case, I will set you up a running version of simulation for Foxy.

**Comment by vkuehn** [comment]
wonderfull news. 
I did not think about the humble version right now but looks like it has already a good reputation already
Thanks for your work !

**Comment by padhupradheep** [comment]
Just follow this tracker and I hope you get the backport soon.

**Comment by vkuehn** [comment]
unfortunatetly not
