### ISSUE TITLE
wrong TF cause robot model to not load properly in multi robot rviz

### ISSUE THREAD

**Issue by VineetTambe** [neobotix/neo_simulation2#68]
Hey,
I was trying to get the single rviz view to work and in doing so noticed a few bugs
Wanted to ask here before jumping to fixing them, just in case they have been addressed in some other branch.

Due to namespace error the tf frames are named as "robot0odom" "robot1odom" instead of "robot0/odom" "robot1/odom" etc.
This is tightly integrated with the reset of the launch files so changing it in simulation.launch.py will not help.
The issue arises because when name space is not specified you do not want any extra "/" but when you specify just the namespace it has to be specifically addressed and an additional "/" must be added if not there.

How do I go about fixing this?
Any suggestions?

**Comment by padhupradheep** [comment]
I didn’t understand the problem. What are the exact bugs that we are talking about ?

Also if it is related to #65, then could we please keep the conversation there ? 😃

**Comment by VineetTambe** [comment]
So the issue I was having was because namespaces somehow not being correctly appended to the frameid's of tf transforms.
I deleted the entire workspace and set everything up again from scratch.
I think updating the neo_fleet_rviz2_plugin somehow fixed the issue.
And now all multirobot stuff works properly without errors in rviz!

**Comment by padhupradheep** [comment]
Awesome. Feel free to open a new issue, if you find something.
