### ISSUE TITLE
converting the environment variable for choosing the robot and map into launch arguments and refactoring the code in simulation and navigation launch files

### ISSUE THREAD

**Issue by AdarshKaran** [neobotix/neo_simulation2#81]
MY_ROBOT and MAP_NAME have to be changed to launch parameters in both simulation.launch.py and navigation.launch.py

**Comment by padhupradheep** [comment]
Once the documentation is finalized, the issue will be closed.

**Comment by padhupradheep** [comment]
tracking documentation in #89
