### ISSUE TITLE
refactor the urdf to xacro code for mpo robots and add logic to include arm

### ISSUE THREAD

**Issue by AdarshKaran** [neobotix/neo_simulation2#85]
Change the urdf to xacro
Split into separate files
Make code modular and efficient 
Add logic to include UR and Elite arms to the xacro

**Comment by padhupradheep** [comment]
These are the combinations:

- [ ] MMO-700 (with UR)
- [ ] MMO-700 (with EC)
- [ ] MMO-500 (with UR)
- [ ] MMO-500 (with EC)
